version: "3.7"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.5
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=Your-Plugin-ID
    volumes:
      - $PWD/grafana/dashboard:/var/lib/grafana/dashboards:z
      - $PWD/plugins:/var/lib/grafana/plugins:z
      - $PWD/provisioning:/var/lib/grafana/provisioning:z